services:
  sorti:
    image: ghcr.io/karaktaka/sorti:latest
    volumes:
      - ./sorti/config.yaml:/app/config.yaml:ro
    environment:
      - EMAIL=${EMAIL:-}
      - PASSWORD=${PASSWORD:-}
      - IMAP_SERVER=${IMAP_SERVER:-}
      - IMAP_PORT=${IMAP_PORT:-}
      - KEYWORDS=${KEYWORDS:-}
      - TAG_NAME=${TAG_NAME:-}
      - EXCLUDED_FOLDERS=${EXCLUDED_FOLDERS:-}
      - TIME_LIMIT=${TIME_LIMIT:-all}
      - INTERVAL=${INTERVAL:-}
    restart: unless-stopped
